using System.ComponentModel;
using System.Windows.Data;
using System.Windows.Markup;

namespace GenSpeed.App;

/// <summary>Langue courante + table de chaînes FR/EN, avec bascule à chaud.</summary>
public sealed class Loc : INotifyPropertyChanged
{
    public static Loc I { get; } = new();
    private Loc() { }

    public event PropertyChangedEventHandler? PropertyChanged;

    /// <summary>0 = FR, 1 = EN.</summary>
    public int Lang { get; private set; } = 0;

    public void SetLanguage(int lang)
    {
        if (lang == Lang) return;
        Lang = lang;
        // Rafraîchit toutes les liaisons d'indexeur (Loc.I["clé"]).
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Lang)));
        LanguageChanged?.Invoke();
    }

    /// <summary>Notifié après changement de langue (pour reconstruire le contenu généré en code).</summary>
    public static event Action? LanguageChanged;

    public string this[string key] =>
        Strings.TryGetValue(key, out var pair) ? pair[Lang] : $"[{key}]";

    /// <summary>Accès direct (code-behind).</summary>
    public static string T(string key) => I[key];

    // [0] = FR, [1] = EN
    private static readonly Dictionary<string, string[]> Strings = new()
    {
        ["subtitle"]    = ["Configurateur de vitesse — Generals Zero Hour", "Speed configurator — Generals Zero Hour"],
        ["help"]        = ["①  Mod(s)   →   ②  Vitesse + Caméra   →   ③  Appliquer            🌐 Vérification multijoueur : optionnelle",
                           "①  Mod(s)   →   ②  Speed + Camera   →   ③  Apply            🌐 Multiplayer check: optional"],
        ["tb.reset"]    = ["↺ Réinit. presets", "↺ Reset presets"],
        ["tb.log"]      = ["◀ Journal", "◀ Log"],
        ["tb.logshow"]  = ["▶ Journal", "▶ Log"],
        ["tb.launch"]   = ["▶  Lancer GenLauncher", "▶  Launch GenLauncher"],
        ["tb.lan"]      = ["🛡 Calculer mon code LAN", "🛡 Compute my LAN code"],
        ["tb.mp"]       = ["🌐 Multijoueur ▾", "🌐 Multiplayer ▾"],
        ["tb.preview"]  = ["🔎 Aperçu ▾", "🔎 Preview ▾"],
        ["tb.config"]   = ["⚙ Config ▾", "⚙ Config ▾"],
        ["tb.diag"]     = ["🩺 Diagnostic mismatch ▾", "🩺 Mismatch diagnostic ▾"],
        ["tb.help"]     = ["❔ Aide", "❔ Help"],
        ["tb.theme"]    = ["Thème :", "Theme:"],

        ["card.mods"]   = ["①  Choisis un ou plusieurs mods", "①  Choose one or more mods"],
        ["card.speed"]  = ["②  Configuration vitesse", "②  Speed configuration"],
        ["card.camera"] = ["③  Configuration caméra", "③  Camera configuration"],
        ["card.apply"]  = ["④  Applique les modifications", "④  Apply the changes"],
        ["card.log"]    = ["Journal d'activité", "Activity log"],

        ["col.mod"]     = ["Jeu / Mod", "Game / Mod"],
        ["col.speed"]   = ["Vitesse", "Speed"],
        ["col.camera"]  = ["Caméra", "Camera"],
        ["col.archives"]= ["Archives", "Archives"],
        ["col.ini"]     = [".ini", ".ini"],
        ["col.patched"] = ["Patchés", "Patched"],
        ["col.code"]    = ["Code", "Code"],

        ["speed.global"]= ["Facteur global :", "Global factor:"],
        ["speed.factor"]= ["Facteur :", "Factor:"],
        ["crud.save"]   = ["💾 Sauvegarder", "💾 Save"],
        ["crud.new"]    = ["＋ Nouveau", "＋ New"],
        ["crud.rename"] = ["✏ Renommer", "✏ Rename"],
        ["crud.delete"] = ["🗑 Supprimer", "🗑 Delete"],

        ["dlg.newspeed"]= ["Nouveau preset vitesse", "New speed preset"],
        ["dlg.newcam"]  = ["Nouveau preset caméra", "New camera preset"],
        ["dlg.name"]    = ["Nom du preset :", "Preset name:"],
        ["dlg.rename"]  = ["Renommer", "Rename"],
        ["dlg.newname"] = ["Nouveau nom :", "New name:"],
        ["msg.locked"]  = ["« {0} » est verrouillé.", "“{0}” is locked."],
        ["msg.camlocked"]=["« Vue par défaut » n'est pas modifiable.", "“Default view” cannot be edited."],
        ["msg.exists"]  = ["Un preset « {0} » existe déjà.", "A preset “{0}” already exists."],
        ["msg.delconfirm"]=["Supprimer « {0} » ?", "Delete “{0}”?"],
        ["msg.minone"]  = ["Il faut au moins un preset.", "At least one preset is required."],
        ["log.psaved"]  = ["💾 Preset « {0} » sauvegardé.", "💾 Preset “{0}” saved."],
        ["log.pnew"]    = ["＋ Preset « {0} » créé.", "＋ Preset “{0}” created."],
        ["log.prenamed"]= ["✏ Preset « {0} » → « {1} ».", "✏ Preset “{0}” → “{1}”."],
        ["log.pdeleted"]= ["🗑 Preset « {0} » supprimé.", "🗑 Preset “{0}” deleted."],
        ["speed.fine"]  = ["Réglage fin par catégorie  (× multiplie,  ÷ divise)",
                           "Fine tuning per category  (× multiply,  ÷ divide)"],
        ["cam.preset"]  = ["Preset caméra :", "Camera preset:"],
        ["cam.default"] = ["Vue par défaut", "Default view"],
        ["campreset.high"] = ["Cam haute", "High cam"],
        ["campreset.max"]  = ["Cam max", "Max cam"],
        ["campreset.far"]  = ["Cam éloignée", "Far cam"],
        ["campreset.sat"]  = ["Vue satellite", "Satellite view"],
        ["cam.fine"]    = ["Réglage fin de la caméra  (vide = défaut du jeu)",
                           "Camera fine tuning  (empty = game default)"],

        ["apply.btn"]   = ["🚀  Appliquer la config (vitesse + caméra) au(x) mod(s) coché(s)",
                           "🚀  Apply config (speed + camera) to checked mod(s)"],
        ["apply.cancel"]= ["↩  Annuler / Revenir à l'original", "↩  Cancel / Revert to original"],

        // Confirmation avant patch
        ["confirm.title"]   = ["Confirmer l'application", "Confirm apply"],
        ["confirm.intro"]   = ["Mods concernés :", "Affected mods:"],
        ["confirm.changes"] = ["Ce que ça va changer en jeu :", "What it changes in-game:"],
        ["confirm.note"]    = ["💾 Une sauvegarde « .speedbak » est créée à côté de CHAQUE fichier modifié (dans {0} et dans les dossiers des mods). « Annuler » les restaure. Une élévation Windows (UAC) sera demandée.",
                               "💾 A “.speedbak” backup is created next to EACH modified file (in {0} and in the mod folders). “Cancel” restores them. A Windows elevation (UAC) prompt will appear."],
        // Effets joueur par catégorie ({0} = facteur)
        ["fx.none"]              = ["Aucun changement (tout est à ×1).", "No change (everything at ×1)."],
        ["fx.deplacement"]      = ["🏃 Déplacement : unités {0}× plus rapides", "🏃 Movement: units {0}× faster"],
        ["fx.projectiles"]      = ["💥 Projectiles {0}× plus rapides", "💥 Projectiles {0}× faster"],
        ["fx.visee"]            = ["🎯 Tourelles : rotation {0}× plus rapide", "🎯 Turrets: {0}× faster rotation"],
        ["fx.construction"]     = ["🏗️ Construction {0}× plus rapide", "🏗️ Construction {0}× faster"],
        ["fx.tir"]              = ["🔫 Cadence de tir {0}× plus rapide", "🔫 Rate of fire {0}× faster"],
        ["fx.pouvoirs"]         = ["⚡ Pouvoirs : recharge {0}× plus rapide", "⚡ Powers: {0}× faster cooldown"],
        ["fx.deploiement"]      = ["📦 Déploiement {0}× plus rapide", "📦 Deployment {0}× faster"],
        ["fx.economie_collecte"]= ["💰 Collecte des ressources {0}× plus rapide", "💰 Resource gathering {0}× faster"],
        ["fx.economie_gain"]    = ["💵 Caisses : valeur ×{0}", "💵 Crates: value ×{0}"],
        ["fx.detection"]        = ["👁️ Vision : portée ×{0}", "👁️ Vision range ×{0}"],
        ["fx.soin"]             = ["➕ Soin {0}× plus efficace", "➕ Healing {0}× more effective"],
        ["fx.merite"]           = ["⭐ XP/mérite ×{0} (promotions plus rapides)", "⭐ XP/merit ×{0} (faster promotions)"],
        ["fx.camera"]           = ["📷 Caméra : {0}", "📷 Camera: {0}"],
        ["cam.custom"]          = ["réglages personnalisés", "custom settings"],
        // ── Info-bulles caméra (langage joueur) ─────────────────────────
        ["tip.cam.CameraPitch"]     = ["Inclinaison de la vue. Valeur plus PETITE = vue plus rasante (on voit l'horizon) ; plus GRANDE = vue plus de dessus, comme une carte.",
                                       "View tilt. SMALLER = more horizontal view (you see the horizon); LARGER = more top-down, like a map."],
        ["tip.cam.CameraHeight"]    = ["Hauteur de la caméra au démarrage. Plus HAUT = tu vois une plus grande zone du champ de bataille.",
                                       "Camera height at start. HIGHER = you see a larger area of the battlefield."],
        ["tip.cam.MaxCameraHeight"] = ["Jusqu'où tu peux DÉZOOMER (t'éloigner). Plus GRAND = tu peux voir de plus loin et plus large.",
                                       "How far you can ZOOM OUT. LARGER = you can see from farther away and wider."],
        ["tip.cam.MinCameraHeight"] = ["Jusqu'où tu peux ZOOMER (te rapprocher). Plus PETIT = tu peux coller au plus près des unités.",
                                       "How far you can ZOOM IN. SMALLER = you can get right up close to the units."],
        ["tip.cam.DrawEntireTerrain"] = ["« Yes » = le jeu dessine TOUTE la carte en permanence : pratique pour voir loin quand on dézoome, MAIS ça peut RALENTIR le jeu si la carte ou le contenu est lourd.\n« No » = plus fluide (les bords lointains peuvent ne pas s'afficher au dézoom max).",
                                       "“Yes” = the game always draws the WHOLE map: handy to see far when zoomed out, BUT it can SLOW the game down if the map or content is heavy.\n“No” = smoother (far edges may not show at max zoom-out)."],
        // ── Info-bulles vitesse (impact en jeu, langage joueur) ──────────
        ["tip.cat.deplacement"]       = ["Vitesse de déplacement des unités. ×2 = elles bougent deux fois plus vite sur le terrain.",
                                         "Unit movement speed. ×2 = they move twice as fast across the map."],
        ["tip.cat.projectiles"]       = ["Vitesse des tirs/projectiles dans l'air. Plus haut = balles et obus atteignent leur cible plus vite.",
                                         "Speed of shots/projectiles in the air. Higher = bullets and shells reach their target faster."],
        ["tip.cat.visee"]             = ["Vitesse de rotation des tourelles. Plus haut = les unités pivotent et visent leur cible plus rapidement.",
                                         "Turret rotation speed. Higher = units turn and aim at their target faster."],
        ["tip.cat.construction"]      = ["Vitesse de construction. ×2 = bâtiments et unités produits deux fois plus vite.",
                                         "Build speed. ×2 = buildings and units produced twice as fast."],
        ["tip.cat.tir"]               = ["Cadence de tir. ×2 = les unités tirent deux fois plus souvent (rechargement deux fois plus court).",
                                         "Rate of fire. ×2 = units shoot twice as often (reload twice as short)."],
        ["tip.cat.pouvoirs"]          = ["Recharge des pouvoirs de général (frappes, renforts…). ×2 = utilisables deux fois plus souvent.",
                                         "General powers recharge (strikes, reinforcements…). ×2 = usable twice as often."],
        ["tip.cat.deploiement"]       = ["Vitesse pour se déployer/replier (ex. artillerie qui s'installe avant de tirer). Plus haut = prêt au combat plus vite.",
                                         "Deploy / pack-up speed (e.g. artillery setting up before firing). Higher = combat-ready faster."],
        ["tip.cat.economie_collecte"] = ["Vitesse de récolte des ressources (collecteurs, raffineries). ×2 = l'argent rentre deux fois plus vite.",
                                         "Resource gathering speed (collectors, refineries). ×2 = money comes in twice as fast."],
        ["tip.cat.economie_gain"]     = ["Valeur de l'argent ramassé (caisses, livraisons). ×2 = chaque ramassage rapporte deux fois plus.",
                                         "Value of collected money (crates, deliveries). ×2 = each pickup is worth twice as much."],
        ["tip.cat.detection"]         = ["Portée de vision des unités. ×2 = elles repèrent les ennemis deux fois plus loin (utile, mais change l'équilibre).",
                                         "Unit vision range. ×2 = they spot enemies twice as far (useful, but changes balance)."],
        ["tip.cat.soin"]              = ["Soins et réparations. Plus haut = les unités sont soignées/réparées davantage et plus vite.",
                                         "Healing and repairs. Higher = units are healed/repaired more and faster."],
        ["tip.cat.merite"]            = ["Gain d'expérience au combat. ×2 = les unités montent en grade (vétéran, élite) deux fois plus vite.",
                                         "Combat experience gain. ×2 = units rank up (veteran, elite) twice as fast."],
        ["patched.flag"]        = ["✅ patché", "✅ patched"],
        ["restore.nothing"]     = ["Aucun des mods sélectionnés n'est patché — rien à restaurer.", "None of the selected mods are patched — nothing to restore."],
        ["log.alreadypatched"]  = ["ℹ {0} mod(s) déjà patché(s) détecté(s) (sauvegardes .speedbak présentes).", "ℹ {0} already-patched mod(s) detected (.speedbak backups present)."],
        // Sélection manuelle du dossier de jeu
        ["pick.title"]          = ["Sélectionne le dossier de Generals Zero Hour", "Select the Generals Zero Hour folder"],
        ["pick.invalid"]        = ["Ce dossier ne ressemble pas à une installation de Zero Hour.\n\nChoisis le dossier qui contient generals.exe / GeneralsZH.exe et le dossier Data — en général :\n...\\steamapps\\common\\Command & Conquer Generals - Zero Hour\n\nAstuce : dans Steam, clic droit sur le jeu → Gérer → Parcourir les fichiers locaux.",
                                   "This folder doesn't look like a Zero Hour install.\n\nPick the folder that contains generals.exe / GeneralsZH.exe and the Data folder — usually:\n...\\steamapps\\common\\Command & Conquer Generals - Zero Hour\n\nTip: in Steam, right-click the game → Manage → Browse local files."],
        ["pick.game.help"]      = ["Choisis le dossier d'installation de Zero Hour : celui qui contient generals.exe / GeneralsZH.exe et le dossier Data.\n\nEn général :\n...\\steamapps\\common\\Command & Conquer Generals - Zero Hour\n\nAstuce : dans Steam, clic droit sur le jeu → Gérer → Parcourir les fichiers locaux.",
                                   "Pick the Zero Hour install folder: the one containing generals.exe / GeneralsZH.exe and the Data folder.\n\nUsually:\n...\\steamapps\\common\\Command & Conquer Generals - Zero Hour\n\nTip: in Steam, right-click the game → Manage → Browse local files."],
        ["pick.mods.help"]      = ["Choisis le dossier des mods de GenLauncher : le dossier « GLM » (ou celui qui le contient).\n\nIl est en général DANS le dossier du jeu :\n...\\Command & Conquer Generals - Zero Hour\\GLM\n\nSi tu ne sais pas où il est : ouvre GenLauncher, ses options/paramètres indiquent le dossier des mods utilisé.",
                                   "Pick GenLauncher's mods folder: the \"GLM\" folder (or the one containing it).\n\nIt's usually INSIDE the game folder:\n...\\Command & Conquer Generals - Zero Hour\\GLM\n\nIf you don't know where it is: open GenLauncher — its options/settings show the mods folder in use."],
        ["pick.mods.title"]     = ["Sélectionne le dossier des mods (GLM)", "Select the mods folder (GLM)"],
        ["pick.mods.invalid"]   = ["Aucun mod GenLauncher trouvé ici. Choisis le dossier « GLM » (ou le dossier qui le contient).",
                                   "No GenLauncher mods found here. Pick the \"GLM\" folder (or the folder that contains it)."],
        // ── Aide globale ────────────────────────────────────────────────
        ["help.title"]   = ["❔ Aide GenSpeed", "❔ GenSpeed Help"],
        ["help.s1.h"]    = ["Qu'est-ce que GenSpeed ?", "What is GenSpeed?"],
        ["help.s1.b"]    = ["GenSpeed accélère le gameplay de C&C Generals Zero Hour et de ses mods en modifiant les fichiers de données (.ini) : unités plus rapides, constructions et recharges plus courtes, presets de caméra. Tout est sauvegardé et réversible en un clic. Il inclut aussi un diagnostic de désync (mismatch) pour le jeu en réseau (LAN).",
                            "GenSpeed speeds up C&C Generals Zero Hour and its mods by editing the game data (.ini) files: faster units, shorter build and reload times, camera presets. Everything is backed up and reversible in one click. It also includes a mismatch (desync) diagnostic for LAN play."],
        ["help.s2.h"]    = ["Démarrage rapide", "Quick start"],
        ["help.s2.b"]    = ["1) Coche un ou plusieurs mods dans la liste.\n2) Choisis une vitesse (Original, Cool, Énervé, Déchaîné) ou règle chaque catégorie.\n3) (Facultatif) Choisis un preset de caméra.\n4) Clique « Appliquer la vitesse » et valide la demande Windows (UAC).\n5) Clique « Lancer GenLauncher » et joue. Pour tout remettre à l'origine : « Annuler ».",
                            "1) Tick one or more mods in the list.\n2) Pick a speed (Original, Cool, Angry, Unleashed) or fine-tune each category.\n3) (Optional) Pick a camera preset.\n4) Click \"Apply speed\" and approve the Windows prompt (UAC).\n5) Click \"Launch GenLauncher\" and play. To restore the original: \"Cancel\"."],
        ["help.s3.h"]    = ["Vitesse & caméra", "Speed & camera"],
        ["help.s3.b"]    = ["Les paliers de vitesse et les presets de caméra sont modifiables (créer / renommer / supprimer) via les boutons 💾 ＋ ✏ 🗑. Pour que la caméra de GenSpeed s'applique correctement, coche « Use default Camera height » dans les options de GenLauncher.",
                            "Speed levels and camera presets are editable (create / rename / delete) via the 💾 ＋ ✏ 🗑 buttons. For GenSpeed's camera to apply correctly, tick \"Use default Camera height\" in GenLauncher's options."],
        ["help.s4.h"]    = ["Dossier du jeu & des mods", "Game & mods folder"],
        ["help.s4.b"]    = ["GenSpeed détecte automatiquement ton installation Steam. Si besoin : menu « ⚙ Config » → « Changer le dossier du jeu » (celui qui contient generals.exe / GeneralsZH.exe et le dossier Data), ou « Changer le dossier des mods (GLM) » si GenLauncher est installé ailleurs. Des conseils d'emplacement s'affichent à l'écran.",
                            "GenSpeed auto-detects your Steam install. If needed: \"⚙ Config\" menu → \"Change game folder\" (the one with generals.exe / GeneralsZH.exe and the Data folder), or \"Change mods folder (GLM)\" if GenLauncher is installed elsewhere. On-screen hints help you locate them."],
        ["help.s5.h"]    = ["LAN & mismatch (désync)", "LAN & mismatch (desync)"],
        ["help.s5.b"]    = ["Règle d'or : sur les deux PC, mêmes versions de jeu et de mods, mêmes réglages GenSpeed, et ne jouez que des cartes que vous avez tous les deux. Une carte que vous ne jouez pas ne cause jamais de désync. Utilise « 🛡 Calculer mon code LAN » pour vérifier que vos installations sont identiques, et « 🩺 Diagnostic mismatch » pour exporter puis comparer deux empreintes et voir exactement ce qui diffère.",
                            "Golden rule: on both PCs, same game and mod versions, same GenSpeed settings, and only play maps you both have. A map you don't play never causes a desync. Use \"🛡 Compute my LAN code\" to check your installs match, and \"🩺 Mismatch diagnostic\" to export then compare two fingerprints and see exactly what differs."],
        ["help.s6.h"]    = ["Sauvegarde, restauration & SmartScreen", "Backup, restore & SmartScreen"],
        ["help.s6.b"]    = ["Avant chaque modification, GenSpeed crée une sauvegarde .speedbak à côté du fichier : « Annuler » restaure l'original à l'identique. Au premier lancement, Windows SmartScreen peut afficher « éditeur inconnu » (l'exe n'est pas signé) → Informations complémentaires → Exécuter quand même.",
                            "Before each change, GenSpeed creates a .speedbak backup next to the file: \"Cancel\" restores the original exactly. On first launch, Windows SmartScreen may show \"unknown publisher\" (the exe isn't signed) → More info → Run anyway."],
        ["help.s7.h"]    = ["À propos", "About"],
        ["help.s7.b"]    = ["GenSpeed v2.0 — gratuit, open-source (licence MIT). Aucune télémétrie, aucune connexion internet. Code écrit par IA, conçu et dirigé par l'auteur. Non affilié à Electronic Arts.\nProjet : github.com/AIPCMEDIA/GenSpeed",
                            "GenSpeed v2.0 — free, open-source (MIT license). No telemetry, no internet connection. Code written by AI, designed and directed by the author. Not affiliated with Electronic Arts.\nProject: github.com/AIPCMEDIA/GenSpeed"],
        ["confirm.ok"]      = ["✅ Valider", "✅ Confirm"],
        ["confirm.cancel"]  = ["Annuler", "Cancel"],
        // Résultat après application
        ["result.title"]    = ["✅ Appliqué", "✅ Applied"],
        ["result.body"]     = ["Configuration appliquée aux mods cochés.\n\nTon code LAN :", "Config applied to checked mods.\n\nYour LAN code:"],
        ["result.launch"]   = ["▶ Lancer GenLauncher", "▶ Launch GenLauncher"],
        ["result.close"]    = ["Fermer", "Close"],
        ["genl.notfound"]   = ["GenLauncher.exe introuvable dans le dossier du jeu.", "GenLauncher.exe not found in the game folder."],
        ["genl.launched"]   = ["▶ GenLauncher lancé.", "▶ GenLauncher launched."],
        ["genl.cancel"]     = ["Lancement de GenLauncher annulé/refusé.", "GenLauncher launch cancelled/denied."],
        // Menu contextuel mods
        ["ctx.open"]        = ["📁 Ouvrir le dossier du mod", "📁 Open mod folder"],
        ["ctx.rename"]      = ["✏ Renommer dans la liste", "✏ Rename in the list"],
        ["rename.mod.msg"]  = ["Nouveau nom affiché (n'affecte pas le jeu ni le code LAN). Laissez le nom par défaut pour le rétablir.",
                               "New display name (does not affect the game or the LAN code). Keep the default name to reset it."],
        ["ctx.copy"]        = ["Copier", "Copy"],
        ["apply.note"]  = ["« Appliquer » modifie le mod (sauvegarde auto). « Annuler » restaure l'original.",
                           "“Apply” modifies the mod (auto-backup). “Cancel” restores the original."],

        // ===== Désinstalleur propre =====
        ["cfg.uninstall"]   = ["🧹 Désinstaller / nettoyer…", "🧹 Uninstall / clean up…"],
        ["clean.title"]     = ["Désinstalleur propre", "Clean uninstaller"],
        ["clean.banner"]    = ["TOUTE la machine est analysée : chaque installation + les traces globales. RIEN n'est supprimé sans ton accord, et tout est sauvegardé avant.",
                               "The WHOLE machine is scanned: every install + global traces. NOTHING is deleted without your consent, and everything is backed up first."],
        ["clean.step0"]     = ["Étape 0 — ferme d'abord le jeu, GenLauncher et WorldBuilder.", "Step 0 — first close the game, GenLauncher and WorldBuilder."],
        ["clean.step"]      = ["Étape {0} — {1}", "Step {0} — {1}"],
        ["clean.proc.warn"] = ["⚠ Le jeu ou un outil semble en cours d'exécution ({0}). Ferme-le avant de nettoyer (sinon fichiers verrouillés). Continuer quand même ?",
                               "⚠ The game or a tool seems to be running ({0}). Close it before cleaning (files would be locked otherwise). Continue anyway?"],
        ["clean.backup.at"] = ["Sauvegarde de secours : {0}", "Safety backup: {0}"],
        ["clean.btn.close"] = ["Fermer", "Close"],
        ["clean.btn.exec"]  = ["🧹 Nettoyer…", "🧹 Clean up…"],
        ["clean.btn.simulate"] = ["👁 Simuler (n'effectue rien)", "👁 Simulate (does nothing)"],
        ["clean.total"]     = ["{0} élément(s) sélectionné(s)  ·  ~{1} à libérer", "{0} item(s) selected  ·  ~{1} to free"],
        ["clean.checkall"]  = ["☑ Tout cocher / décocher (TOUTE la machine)", "☑ Check / uncheck all (the WHOLE machine)"],
        ["clean.sec.global"] = ["🌐 Traces globales (registre, Documents, raccourcis, Windows)", "🌐 Global traces (registry, Documents, shortcuts, Windows)"],
        ["cfg.addinstall"]  = ["➕ Ajouter une installation…", "➕ Add an install…"],
        ["inst.add.help"]   = ["Les installs Steam et celles du registre EA sont détectées AUTOMATIQUEMENT. N'ajoute ici qu'une copie manuelle (dossier hors Steam, fork copié ailleurs…).",
                               "Steam installs and EA-registry installs are detected AUTOMATICALLY. Only add a manual copy here (non-Steam folder, fork copied elsewhere…)."],
        ["inst.added"]      = ["➕ Installation ajoutée : {0}", "➕ Install added: {0}"],
        ["log.installs.found"] = ["🖥 {0} installation(s) détectée(s).", "🖥 {0} install(s) detected."],
        ["diag.pick.title"] = ["Quelle installation ?", "Which install?"],
        ["diag.pick.msg"]   = ["L'empreinte mismatch est calculée PAR installation (celle que vous jouez en LAN) :",
                               "The mismatch fingerprint is computed PER install (the one you play in LAN):"],
        ["clean.risk.sur"]       = ["Sûr", "Safe"],
        ["clean.risk.attention"] = ["Attention", "Caution"],
        ["clean.risk.danger"]    = ["Danger", "Danger"],
        ["clean.checkcat"]       = ["Cocher / décocher toute cette catégorie", "Check / uncheck this whole category"],
        ["clean.gl.note"]   = ["💡 Pour retirer un mod/addon en GARDANT GenLauncher, son désinstalleur intégré est le plus propre. GenSpeed le fait aussi (pratique en nettoyage total, ou si GenLauncher ne se lance plus) et met son catalogue à jour.",
                               "💡 To remove a mod/addon while KEEPING GenLauncher, its built-in uninstaller is the cleanest. GenSpeed can also do it (handy for a full cleanup, or if GenLauncher no longer launches) and updates its catalog."],
        ["clean.gl.open"]   = ["Ouvrir GenLauncher", "Open GenLauncher"],
        ["clean.infoonly"]  = ["info — non supprimable ici", "info — not removable here"],
        ["clean.nothing"]   = ["Rien à nettoyer pour cette installation. 👍", "Nothing to clean for this install. 👍"],
        ["clean.scanning"]  = ["🔎 Analyse de l'installation et des traces…", "🔎 Scanning install and leftovers…"],
        ["clean.none.sel"]  = ["Aucun élément sélectionné — rien à faire.", "No item selected — nothing to do."],
        ["clean.sim.head"]  = ["👁 SIMULATION — voici ce qui SERAIT fait (aucune modification) :", "👁 SIMULATION — here is what WOULD be done (no change):"],
        ["clean.sim.foot"]  = ["👁 Fin de simulation. Sauvegarde prévue : {0}", "👁 End of simulation. Planned backup: {0}"],
        ["clean.confirm"]   = ["Confirmer le nettoyage de {0} élément(s) ?\n\nTout sera d'abord sauvegardé dans :\n{1}",
                               "Confirm cleanup of {0} item(s)?\n\nEverything will be backed up first to:\n{1}"],
        ["clean.running"]   = ["🧹 Nettoyage en cours (sauvegarde puis suppression)…", "🧹 Cleaning up (backup then removal)…"],
        ["clean.report"]    = ["Terminé : {0} action(s), {1} erreur(s), ~{2} libéré(s).\n\nSauvegarde de secours :\n{3}\n\n(Voir RESTORE.txt pour restaurer.)",
                               "Done: {0} action(s), {1} error(s), ~{2} freed.\n\nSafety backup:\n{3}\n\n(See RESTORE.txt to restore.)"],
        ["clean.steam.ask"] = ["Lancer la désinstallation du jeu via Steam (AppID {0}) ? Steam affichera sa propre confirmation.",
                               "Launch the game's uninstall via Steam (AppID {0})? Steam will show its own confirmation."],
        ["clean.steam.started"] = ["💨 Désinstallation Steam lancée (AppID {0}) — confirme dans la fenêtre Steam.",
                                   "💨 Steam uninstall launched (AppID {0}) — confirm in the Steam window."],
        ["clean.steam.residue"] = ["💡 Steam ne supprime que SES fichiers : des ajouts tiers (addons, caches…) peuvent rester dans le dossier. Relance le désinstalleur après la fin de Steam — le dossier restant sera alors proposé en suppression normale.",
                                   "💡 Steam only removes ITS OWN files: third-party additions (addons, caches…) may remain in the folder. Re-run the uninstaller after Steam finishes — the leftover folder will then be offered for normal deletion."],

        // Catégories du désinstalleur (clé = nom d'enum CleanupCategory)
        ["clean.cat.Jeu"]         = ["🎮 Jeu", "🎮 Game"],
        ["clean.cat.Mods"]        = ["🧩 Mods (GLM)", "🧩 Mods (GLM)"],
        ["clean.cat.GenTool"]     = ["🛠 GenTool (DLL)", "🛠 GenTool (DLLs)"],
        ["clean.cat.GenLauncher"] = ["🚀 GenLauncher", "🚀 GenLauncher"],
        ["clean.cat.GenPatcher"]  = ["🩹 GenPatcher", "🩹 GenPatcher"],
        ["clean.cat.Registre"]    = ["🗝 Registre", "🗝 Registry"],
        ["clean.cat.Raccourcis"]  = ["🖇 Raccourcis", "🖇 Shortcuts"],
        ["clean.cat.AppCompat"]   = ["🧭 Compatibilité (AppCompatFlags)", "🧭 Compatibility (AppCompatFlags)"],
        ["clean.cat.Steam"]       = ["💨 Steam", "💨 Steam"],
        ["clean.cat.GenSpeed"]    = ["🟦 GenSpeed", "🟦 GenSpeed"],
        ["clean.cat.Systeme"]     = ["⚙ Système", "⚙ System"],
        ["clean.cat.Joueur"]      = ["📁 Données joueur (Documents)", "📁 Player data (Documents)"],
        ["clean.cat.TracesWin"]   = ["🧹 Traces Windows (diagnostics)", "🧹 Windows traces (diagnostics)"],

        // Méthodes (clé = nom d'enum CleanupMethod)
        ["clean.method.Laisser"]              = ["Laisser", "Leave"],
        ["clean.method.Desactiver"]           = ["Désactiver (renommer .off)", "Disable (rename .off)"],
        ["clean.method.SauvegarderSupprimer"] = ["Sauvegarder puis supprimer", "Backup then delete"],
        ["clean.method.SupprimerDirect"]      = ["Supprimer directement", "Delete directly"],
        ["clean.method.DesinstallerSteam"]    = ["Désinstaller via Steam (officiel)", "Uninstall via Steam (official)"],
        ["clean.method.all"] = ["⚙ Méthode pour tout (éléments compatibles) :", "⚙ Method for everything (compatible items):"],

        // Explications par élément
        ["clean.explain.d3d8"]     = ["GenTool (proxy DirectX 8 dans le dossier du jeu). Le retirer = le jeu retombe sur le DirectX 8 de Windows (vérifié automatiquement après nettoyage) ; seules les fonctions GenTool sont perdues. Conseillé : Désactiver (réversible).",
                                      "GenTool (DirectX 8 proxy in the game folder). Removing it = the game falls back to Windows' own DirectX 8 (verified automatically after cleanup); only GenTool features are lost. Recommended: Disable (reversible)."],
        ["clean.dx.checking"]   = ["🔎 Vérification du DirectX 8 système (celui de Windows)…", "🔎 Checking the system DirectX 8 (Windows' own)…"],
        ["clean.dx.ok"]         = ["DirectX 8 d'origine Windows vérifié — le jeu est bon. ({0})", "Genuine Windows DirectX 8 verified — the game is fine. ({0})"],
        ["clean.dx.bad"]        = ["DirectX 8 système anormal : {0}", "System DirectX 8 looks abnormal: {0}"],
        ["clean.dx.sfc.ask"]    = ["Le DirectX 8 de Windows semble anormal. Lancer la réparation officielle de Windows (« sfc /scannow ») ?\n\n⚠ C'est LA méthode sûre (aucun téléchargement), mais ça peut être LONG (souvent 5 à 20 minutes). Une fenêtre noire va s'ouvrir : laisse-la travailler jusqu'à 100 %.",
                                   "Windows' DirectX 8 looks abnormal. Launch Windows' official repair (“sfc /scannow”)?\n\n⚠ This is THE safe method (no download), but it can take a WHILE (often 5–20 minutes). A black window will open: let it run to 100%."],
        ["clean.dx.sfc.started"] = ["🛠 Réparation Windows lancée (sfc /scannow) — laisse la fenêtre aller jusqu'à 100 %.", "🛠 Windows repair started (sfc /scannow) — let the window reach 100%."],
        ["clean.log.saved"]      = ["📄 Journal enregistré : {0}", "📄 Log saved: {0}"],
        ["clean.explain.gentool"]  = ["Composant GenTool. Sans danger à retirer (sauvegarde recommandée).", "GenTool component. Safe to remove (backup recommended)."],
        ["clean.explain.dbghelp"]  = ["Gestionnaire de crash (GenTool) ou DLL renommée par GenPatcher. À retirer avec précaution.", "Crash handler (GenTool) or DLL renamed by GenPatcher. Remove with care."],
        ["clean.explain.glfolder"] = ["Données et config de GenLauncher (catalogue, images, GenLauncherCfg.yaml).", "GenLauncher data and config (catalog, images, GenLauncherCfg.yaml)."],
        ["clean.explain.genlauncher"] = ["Exécutable / fichiers de GenLauncher.", "GenLauncher executable / files."],
        ["clean.explain.launcherdir"] = ["Dossier de ressources du lanceur.", "Launcher resources folder."],
        ["clean.explain.moddedexe"] = ["Exe moteur modifié (fork) utilisé par l'option « Use modded .exe » de GenLauncher. Inutile sans GenLauncher.",
                                       "Modified engine exe (fork) used by GenLauncher's “Use modded .exe” option. Useless without GenLauncher."],
        ["clean.explain.glm"]      = ["Tous les mods téléchargés par GenLauncher (peut peser plusieurs Go). Les retirer = retélécharger plus tard.",
                                      "All mods downloaded by GenLauncher (can be several GB). Removing = re-download later."],
        ["clean.explain.mod"]      = ["Mod GenLauncher (inclut ses versions, addons et patches). Re-téléchargeable plus tard.",
                                      "GenLauncher mod (includes its versions, addons and patches). Re-downloadable later."],
        ["clean.explain.modshared"] = ["Dossier partagé GenLauncher (addons/patches/outils communs). Re-téléchargeable.",
                                       "Shared GenLauncher folder (common addons/patches/tools). Re-downloadable."],
        ["clean.explain.addon"]    = ["Addon d'un mod (fichiers .gib). Le retirer garde le mod ; GenLauncher sera mis à jour pour ne plus le croire installé.",
                                      "A mod's addon (.gib files). Removing it keeps the mod; GenLauncher will be updated so it no longer thinks it's installed."],
        ["clean.explain.patch"]    = ["Patch d'un mod (fichiers .gib). Le retirer garde le mod ; GenLauncher sera mis à jour en conséquence.",
                                      "A mod's patch (.gib files). Removing it keeps the mod; GenLauncher will be updated accordingly."],
        ["clean.explain.speedbak"] = ["Sauvegardes GenSpeed (.speedbak) : permettent d'annuler les patchs de vitesse. Les supprimer = perte de cette restauration.",
                                      "GenSpeed backups (.speedbak): allow undoing speed patches. Deleting = losing that restore."],
        ["clean.explain.gscfg"]    = ["RÉINITIALISE GenSpeed : supprime sa config (presets, cache). GenSpeed reste installé et repart aux réglages par défaut.",
                                      "RESETS GenSpeed: deletes its config (presets, cache). GenSpeed stays installed and returns to default settings."],
        ["clean.explain.shortcut"] = ["Raccourci lié au jeu / aux mods.", "Shortcut related to the game / mods."],
        ["clean.explain.eareg"]    = ["Clé registre EA (chemin d'install). La retirer empêche les lanceurs de trouver le jeu — utile seulement en désinstallation totale.",
                                      "EA registry key (install path). Removing it stops launchers from finding the game — only for full uninstall."],
        ["clean.explain.earoot"]   = ["Racine « EA Games » devenue une coquille vide : il n'y reste que des sous-clés du jeu, toutes vides (aucune valeur). Sûr à retirer — Steam la recrée au besoin. Conservée si un autre jeu EA y vit encore.",
                                      "“EA Games” root now an empty shell: only game subkeys remain, all empty (no values). Safe to remove — Steam recreates it if needed. Kept if another EA game still lives there."],
        ["clean.explain.appcompat"] = ["Réglage de compatibilité Windows lié à un exe du jeu.", "Windows compatibility setting tied to a game exe."],
        ["clean.explain.appcompat.orphan"] = ["Réglage de compatibilité ORPHELIN (l'exe n'existe plus). Sans danger à retirer.", "ORPHAN compatibility setting (the exe no longer exists). Safe to remove."],
        ["clean.explain.steam"]    = ["Jeu installé par Steam. Coche pour lancer sa désinstallation OFFICIELLE via Steam à la fin du nettoyage — GenSpeed ne supprime jamais ces fichiers à la main (Steam le croirait encore installé).",
                                      "Game installed by Steam. Check to launch its OFFICIAL uninstall via Steam at the end of the cleanup — GenSpeed never deletes these files by hand (Steam would still think it's installed)."],
        ["clean.explain.gamedir"]  = ["Dossier du jeu (hors Steam). Le supprimer retire le jeu et tout son contenu.", "Game folder (non-Steam). Removing it deletes the game and all its content."],
        ["clean.explain.vcredist"] = ["Redistribuable système partagé par d'autres logiciels. Ne pas retirer ici — passe par « Programmes et fonctionnalités » de Windows.",
                                      "System redistributable shared by other software. Don't remove here — use Windows “Programs and Features”."],
        ["clean.explain.genpatcher"]   = ["GenPatcher (exe ou dossier téléchargé). Le retirer n'annule pas ses correctifs déjà appliqués (patch, redists, registre).",
                                          "GenPatcher (downloaded exe or folder). Removing it does not undo its already-applied fixes (patch, redists, registry)."],
        ["clean.explain.genpatcher.data"] = ["Dossier laissé par GenPatcher dans les données du jeu (Documents). Résidu — sans danger à retirer.",
                                             "Folder left by GenPatcher in the game data (Documents). Leftover — safe to remove."],
        ["clean.explain.browserengine"] = ["DLL gérée par GenPatcher. À retirer avec précaution.", "DLL handled by GenPatcher. Remove with care."],
        ["clean.explain.datafolder"] = ["TOUT le dossier de données du jeu (Documents) : maps, replays, sauvegardes, réglages. Option « table rase » — données perso, décoché par défaut.",
                                        "The WHOLE game data folder (Documents): maps, replays, saves, settings. “Clean slate” option — personal data, unchecked by default."],
        ["clean.explain.usermaps"] = ["TES cartes personnelles / téléchargées (Documents). Données perso — décoché par défaut.",
                                      "YOUR personal / downloaded maps (Documents). Personal data — unchecked by default."],
        ["clean.explain.replays"]  = ["TES parties enregistrées (replays). Données perso — décoché par défaut.", "YOUR recorded games (replays). Personal data — unchecked by default."],
        ["clean.explain.saves"]    = ["TES sauvegardes solo. Données perso — décoché par défaut.", "YOUR single-player saves. Personal data — unchecked by default."],
        ["clean.explain.screenshots"] = ["Captures d'écran (souvent GenTool). Données perso — décoché par défaut.", "Screenshots (often GenTool). Personal data — unchecked by default."],
        ["clean.explain.options"]  = ["Réglages du jeu (résolution, audio, réseau…). Le retirer remet les options par défaut.", "Game settings (resolution, audio, network…). Removing it resets options to default."],
        ["clean.explain.mappreviews"] = ["Aperçus de cartes générés par le jeu. Régénérés au besoin — sans danger.", "Map previews generated by the game. Regenerated as needed — safe."],
        ["clean.explain.crashdumps"]  = ["Rapports de plantage du jeu (diagnostic). Sans danger à retirer.", "Game crash dumps (diagnostics). Safe to remove."],
        ["clean.explain.installmaps"] = ["Cartes dans le dossier du jeu (officielles + ajoutées). Retirer peut enlever des cartes du jeu de base — décoché par défaut.",
                                         "Maps in the game folder (official + added). Removing may delete base-game maps — unchecked by default."],
        ["clean.explain.wintrace"] = ["Journal de diagnostic créé automatiquement par WINDOWS (pas par l'outil). Inoffensif — Windows le recrée au besoin.",
                                      "Diagnostic log created automatically by WINDOWS (not by the tool). Harmless — Windows recreates it if needed."],
        ["clean.explain.gibassoc"] = ["Association de type de fichier .gib (créée en ouvrant un .gib). Sans danger à retirer.",
                                      "File-type association for .gib (created by opening a .gib). Safe to remove."],
        ["clean.explain.recent"]   = ["Lien « fichiers récents » de Windows vers GenLauncher. Sans danger à retirer.",
                                      "Windows “recent files” link to GenLauncher. Safe to remove."],

        // Catégories
        ["cat.deplacement"]      = ["Déplacement", "Movement"],
        ["cat.projectiles"]      = ["Projectiles", "Projectiles"],
        ["cat.visee"]            = ["Visée (tourelles)", "Aiming (turrets)"],
        ["cat.construction"]     = ["Construction", "Construction"],
        ["cat.tir"]              = ["Tir", "Firing"],
        ["cat.pouvoirs"]         = ["Pouvoirs (recharge)", "Powers (cooldown)"],
        ["cat.deploiement"]      = ["Déploiement", "Deployment"],
        ["cat.economie_collecte"]= ["Collecte", "Gathering"],
        ["cat.economie_gain"]    = ["Gain caisse", "Crate value"],
        ["cat.detection"]        = ["Vision", "Vision"],
        ["cat.soin"]             = ["Soin", "Healing"],
        ["cat.merite"]           = ["Mérite (XP)", "Merit (XP)"],

        // Presets vitesse
        ["preset.0"] = ["Original", "Original"],
        ["preset.1"] = ["Cool", "Cool"],
        ["preset.2"] = ["Énervé", "Angry"],
        ["preset.3"] = ["Déchaîné", "Unleashed"],

        // Hints caméra
        ["cam.hint.pitch"] = ["37.5 (inclinaison)", "37.5 (pitch)"],
        ["cam.hint.h"]     = ["232 (hauteur de départ)", "232 (start height)"],
        ["cam.hint.max"]   = ["310 (zoom max, ~800 conseillé)", "310 (max zoom, ~800 advised)"],
        ["cam.hint.min"]   = ["120 (zoom min)", "120 (min zoom)"],
        ["cam.hint.terrain"]= ["Yes/No (afficher tout le terrain)", "Yes/No (draw entire terrain)"],

        ["orig"] = ["Original", "Original"],
        ["vanilla.name"] = ["🎮 Jeu de base (sans mod)", "🎮 Base game (no mod)"],
        ["vanilla.ini"]  = ["🎮 Jeu de base — fichiers INI", "🎮 Base game — INI files"],

        // Aperçu
        ["preview.key"]  = ["Valeurs clés", "Key values"],
        ["preview.full"] = ["🔍 Exhaustif", "🔍 Exhaustive"],
        ["preview.mod"]  = ["🟢 Modifs seulement", "🟢 Changes only"],
        ["preview.title"]= ["Aperçu — {0}", "Preview — {0}"],
        ["preview.nosel"]= ["Coche d'abord un mod dans la liste.", "Check a mod in the list first."],
        ["preview.none"] = ["Aucune variable trouvée.", "No variable found."],
        ["preview.notpatched"]=["Ce mod n'est pas patché : aucune modification à afficher.",
                                "This mod isn't patched: nothing to show."],
        ["preview.summary"]=["{0} variable(s){1}", "{0} variable(s){1}"],
        ["preview.changed"]=[", {0} modifiée(s)", ", {0} changed"],
        ["preview.col.var"]= ["Variable", "Variable"],
        ["preview.col.orig"]=["Original", "Original"],
        ["preview.col.cur"]= ["Actuel", "Current"],
        ["preview.col.loc"]= ["Localisation", "Location"],

        // Dernier replay
        ["mp.replay"]    = ["📜 Dernier replay (version + map)", "📜 Last replay (version + map)"],
        ["replay.none"]  = ["Aucun replay trouvé. Joue une partie d'abord.", "No replay found. Play a game first."],
        ["replay.title"] = ["📜 Dernière partie", "📜 Last game"],
        ["replay.body"]  = ["VERSION (à comparer entre joueurs) :\n→  {0}\n\nMap : {1}\nCRC map : {2}\nJoueurs : {3}\n\nPour jouer en LAN sans mismatch, la ligne VERSION et le CRC map doivent être IDENTIQUES chez tous.",
                            "VERSION (compare between players):\n→  {0}\n\nMap: {1}\nMap CRC: {2}\nPlayers: {3}\n\nTo play LAN without mismatch, the VERSION line and map CRC must be IDENTICAL for everyone."],

        // Diagnostic mismatch
        ["diag.export"]  = ["🩺 Exporter mon diagnostic…", "🩺 Export my diagnostic…"],
        ["diag.compare"] = ["🔍 Comparer avec un ami…", "🔍 Compare with a friend…"],
        ["diag.title"]   = ["🩺 Diagnostic mismatch", "🩺 Mismatch diagnostic"],
        ["diag.badfile"] = ["Ce fichier n'est pas un diagnostic de synchro GenSpeed.\nDemande à l'autre joueur de l'exporter depuis « 🩺 Diagnostic ».",
                            "This file is not a GenSpeed sync diagnostic.\nAsk the other player to export it from “🩺 Diagnostic”."],
        ["diag.exported"]= ["🩺 Diagnostic exporté : {0}", "🩺 Diagnostic exported: {0}"],
        ["diag.ndiff"]   = ["{0} différence(s) détectée(s) :", "{0} difference(s) found:"],
        ["diag.allok"]   = ["✅ Tout le contenu déterminant est identique. Un désync viendrait alors du CPU/réseau, pas des fichiers.",
                            "✅ All deciding content is identical. A desync would then come from CPU/network, not files."],
        ["diag.crit"]    = ["❌ Mismatch quasi certain — {0} élément(s) déterminant(s) diffèrent (jeu / INI / mod).",
                            "❌ Mismatch almost certain — {0} deciding item(s) differ (game / INI / mod)."],
        ["diag.warn"]    = ["⚠️ Jeu identique, mais {0} map(s)/addon(s) diffèrent — mismatch possible si concernés.",
                            "⚠️ Same game, but {0} map(s)/add-on(s) differ — possible mismatch if used."],
        ["diag.legend"]  = ["❌ critique = empêche la synchro   ·   ⚠ attention = map/addon   ·   ℹ info = contexte",
                            "❌ critical = blocks sync   ·   ⚠ warning = map/add-on   ·   ℹ info = context"],
        ["diag.col.sev"] = ["Gravité", "Severity"],
        ["diag.col.item"]= ["Élément", "Item"],
        ["diag.col.detail"]=["Détail (toi ↔ ami)", "Detail (you ↔ friend)"],
        ["sev.crit"]     = ["❌ CRITIQUE", "❌ CRITICAL"],
        ["sev.warn"]     = ["⚠ ATTENTION", "⚠ WARNING"],
        ["sev.info"]     = ["ℹ INFO", "ℹ INFO"],
        ["st.diff"]      = ["DIFFÉRENT", "DIFFERENT"],
        ["st.absme"]     = ["absent chez toi", "missing on your side"],
        ["st.absother"]  = ["absent chez l'ami", "missing on friend's side"],
        ["sec.base"]     = ["Données de base", "Base game data"],
        ["sec.ini"]      = ["INI lâches", "Loose INI"],
        ["sec.maps"]     = ["Maps", "Maps"],
        ["sec.gentool"]  = ["GenTool / overlay", "GenTool / overlay"],
        ["sec.components"]= ["Composants", "Components"],
        ["sec.mod"]      = ["Mod", "Mod"],

        // Code LAN
        ["lan.computing"]= ["🛡 Calcul du code LAN…", "🛡 Computing LAN code…"],
        ["lan.done"]     = ["🛡 Ton code LAN : {0}   ({1} fichiers, {2} Mo)", "🛡 Your LAN code: {0}   ({1} files, {2} MB)"],

        // Menu config
        ["cfg.gamedir"]  = ["📁 Changer le dossier du jeu", "📁 Change game folder"],
        ["cfg.modsdir"]  = ["🧩 Changer le dossier des mods (GLM)", "🧩 Change mods folder (GLM)"],
        ["cfg.modsdir.set"] = ["Dossier des mods : {0}", "Mods folder: {0}"],
        ["cfg.installs"]    = ["🗂 Installations…", "🗂 Installations…"],
        ["inst.title"]      = ["Installations", "Installations"],
        ["inst.msg"]        = ["Choisis l'installation active, ou ajoutes-en une (jeu de base, mod autonome type Reborn Omega…). Le « ● » marque l'active.",
                               "Pick the active installation, or add one (base game, standalone mod like Reborn Omega…). The “●” marks the active one."],
        ["inst.add"]        = ["➕ Ajouter une installation…", "➕ Add an installation…"],
        ["inst.switched"]   = ["🗂 Installation active : {0}", "🗂 Active installation: {0}"],
        ["inst.type.orig"]  = ["🎮 Jeu d'origine", "🎮 Original game"],
        ["inst.type.genl"]  = ["🧩 GenLauncher", "🧩 GenLauncher"],
        ["inst.type.fork"]  = ["🔧 Mod autonome / fork", "🔧 Standalone / fork mod"],
        ["launch.pick.title"] = ["Quel lanceur ?", "Which launcher?"],
        ["launch.pick.msg"]   = ["Plusieurs exécutables possibles dans cette installation. Choisis celui à lancer (mémorisé pour la prochaine fois) :",
                                 "Several possible executables in this install. Pick the one to launch (remembered next time):"],
        ["launch.started"]    = ["▶ Lancé : {0}", "▶ Launched: {0}"],
        ["cfg.launcher"]      = ["🎮 Changer le lanceur (mod coché)", "🎮 Change launcher (checked mod)"],
        ["launch.change.msg"] = ["Choisis l'exécutable de lancement pour : {0}\n(mémorisé pour ce mod ; tu peux le rechanger ici quand tu veux) :",
                                 "Pick the launch executable for: {0}\n(remembered for this mod; you can change it here anytime):"],
        ["launch.set"]        = ["▶ Lanceur défini pour {1} : {0}", "▶ Launcher set for {1}: {0}"],
        ["launch.nomod"]      = ["(aucun mod coché)", "(no mod checked)"],
        ["sel.all.tip"]       = ["Tout cocher / décocher", "Check / uncheck all"],
        ["cfg.reset"]    = ["↺ Réinitialiser les champs", "↺ Reset fields"],
        ["cfg.export"]   = ["📤 Exporter la config…", "📤 Export config…"],
        ["cfg.import"]   = ["📥 Importer une config…", "📥 Import config…"],
        ["cfg.reset.done"]=["↺ Champs réinitialisés.", "↺ Fields reset."],
        ["cfg.exported"] = ["📤 Config exportée : {0}", "📤 Config exported: {0}"],
        ["cfg.imported"] = ["📥 Config importée : {0}", "📥 Config imported: {0}"],

        // Journal
        ["log.start"]    = ["GenSpeed (.NET 8 / WPF) démarré.", "GenSpeed (.NET 8 / WPF) started."],
        ["log.detected"] = ["{0} cible(s) détectée(s).", "{0} target(s) detected."],
        ["log.gamedir"]  = ["Dossier jeu : {0}", "Game folder: {0}"],
        ["log.modsextra"]= ["+{0} mod(s) trouvé(s) dans : {1}", "+{0} mod(s) found in: {1}"],
        ["log.nogame"]   = ["Dossier du jeu introuvable (sélection manuelle à venir).",
                            "Game folder not found (manual selection coming soon)."],
        ["log.nosel"]    = ["Aucun mod coché.", "No mod checked."],
        ["log.applying"] = ["⏳ Application en cours (autorise l'élévation UAC)…",
                            "⏳ Applying (allow the UAC prompt)…"],
        ["log.restoring"]= ["⏳ Restauration en cours (autorise l'élévation UAC)…",
                            "⏳ Restoring (allow the UAC prompt)…"],
        ["log.uaccancel"]= ["Élévation refusée/annulée — rien n'a été modifié.",
                            "Elevation declined/cancelled — nothing changed."],
        ["log.noresult"] = ["Aucun résultat renvoyé par l'opération.", "No result returned by the operation."],
        ["log.applied"]  = ["✅ Configuration appliquée aux mods cochés.", "✅ Configuration applied to checked mods."],
        ["log.restored"] = ["↩ Mods restaurés à l'original.", "↩ Mods restored to original."],
        ["log.filespatched"] = ["fichier(s) patché(s)", "file(s) patched"],
        ["log.restoredmod"]  = ["restauré", "restored"],
    };
}

/// <summary>Extension de balisage : {l:Tr clé} → liaison vers Loc.I["clé"] (mise à jour à chaud).</summary>
public sealed class TrExtension : MarkupExtension
{
    public string Key { get; set; } = "";
    public TrExtension() { }
    public TrExtension(string key) => Key = key;

    public override object ProvideValue(IServiceProvider serviceProvider)
    {
        var binding = new Binding($"[{Key}]") { Source = Loc.I, Mode = BindingMode.OneWay };
        return binding.ProvideValue(serviceProvider);
    }
}
